### ISSUE TITLE
Type matching problem on ATEvent+LocalNofifications

### ISSUE THREAD

**Issue by Narayane** [adriantofan/ATCalendar#1]
Hi,

I have this error when I try to use your ATCalendar 0.1.19 in Xcode 7.2.1.

![atcalendar_error](https://cloud.githubusercontent.com/assets/4921308/13350752/3e479d14-dc82-11e5-8624-27dcbba9db45.png)

Can you help me ?

Thanks.

**Comment by adriantofan** [comment]
Yes, I've fixed it for you in the .21 release.

**Comment by Narayane** [comment]
Thanks
